# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/config/logging_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow_serving.config import log_collector_config_pb2 as tensorflow__serving_dot_config_dot_log__collector__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.tensorflow_serving/config/logging_config.proto\x12\x12tensorflow.serving\x1a\x34tensorflow_serving/config/log_collector_config.proto\"\x92\x01\n\x0eSamplingConfig\x12\x15\n\rsampling_rate\x18\x01 \x01(\x01\x12\x12\n\nattributes\x18\x02 \x01(\x05\"U\n\nAttributes\x12\x10\n\x0c\x41TTR_DEFAULT\x10\x00\x12\x17\n\x13\x41TTR_REQUEST_ORIGIN\x10\x01\x12\x1c\n\x18\x41TTR_REQUEST_CRITICALITY\x10\x02\"\x92\x01\n\rLoggingConfig\x12\x44\n\x14log_collector_config\x18\x01 \x01(\x0b\x32&.tensorflow.serving.LogCollectorConfig\x12;\n\x0fsampling_config\x18\x02 \x01(\x0b\x32\".tensorflow.serving.SamplingConfigB\x03\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensorflow_serving.config.logging_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _SAMPLINGCONFIG._serialized_start=125
  _SAMPLINGCONFIG._serialized_end=271
  _SAMPLINGCONFIG_ATTRIBUTES._serialized_start=186
  _SAMPLINGCONFIG_ATTRIBUTES._serialized_end=271
  _LOGGINGCONFIG._serialized_start=274
  _LOGGINGCONFIG._serialized_end=420
# @@protoc_insertion_point(module_scope)
